/* Voice engine.
   Best:    a recorded talking-avatar VIDEO of Ravichandra (assets/video/<id>.mp4, his cloned voice).
   Next:    pre-rendered natural neural voice clips (assets/voice/<id>.mp3 + .json word timings),
            generated by tools/gen_voice.py. Lip-sync is driven by the real audio waveform.
   Fallback: browser speech synthesis (for any text that has no clip, e.g. LLM answers). */

import { hasClip, playClip, stopClip } from './presenter.js';

const $ = (s) => document.querySelector(s);
const listeners = new Set();
export const voiceState = { speaking: false, open: 0, who: null, id: null, muted: false };
export const onVoice = (fn) => listeners.add(fn);
const emit = (e) => listeners.forEach((fn) => fn(e));

/* ---------- audio graph ---------- */
const audio = new Audio();
audio.preload = 'auto';
let ctx, analyser, buf;
export function unlockAudio() {
  try {
    if (!ctx) {
      ctx = new (window.AudioContext || window.webkitAudioContext)();
      const srcNode = ctx.createMediaElementSource(audio);
      analyser = ctx.createAnalyser();
      analyser.fftSize = 1024;
      analyser.smoothingTimeConstant = 0.2;
      srcNode.connect(analyser); analyser.connect(ctx.destination);
      buf = new Float32Array(analyser.fftSize);
    }
    if (ctx.state === 'suspended') ctx.resume();
  } catch (e) { console.warn('audio unlock failed', e); }
  // prime speech synthesis too (iOS needs a gesture)
  try { speechSynthesis.speak(new SpeechSynthesisUtterance('')); } catch {}
}

const metaCache = new Map();
async function meta(id) {
  if (!metaCache.has(id)) metaCache.set(id, fetch(`assets/voice/${id}.json`).then((r) => (r.ok ? r.json() : null)).catch(() => null));
  return metaCache.get(id);
}
export const clipInfo = meta;
export function preload(ids) { ids.forEach((id) => { meta(id); const l = document.createElement('link'); l.rel = 'prefetch'; l.href = `assets/voice/${id}.mp3`; document.head.append(l); }); }

/* ---------- captions ---------- */
let words = [], capText = '';
let videoT = -1;
function setCaption(w, text) {
  words = w; capText = text;
  const el = $('#captionText');
  if (!el) return;
  el.innerHTML = w.length
    ? w.map((x, i) => `<span class="w" data-i="${i}">${x[2]}</span>`).join(' ')
    : text.split(/\s+/).map((x, i) => `<span class="w" data-i="${i}">${x}</span>`).join(' ');
}
let lastIdx = -1;
function updateCaption(t) {
  if (!words.length) return;
  let idx = -1;
  for (let i = 0; i < words.length; i++) if (t >= words[i][0]) idx = i;
  if (idx === lastIdx) return;
  lastIdx = idx;
  // keep a ~16 word window visible
  const el = $('#captionText');
  const start = Math.max(0, idx - 8), end = Math.min(words.length, start + 18);
  el.querySelectorAll('.w').forEach((s, i) => {
    s.style.display = i >= start && i < end ? '' : 'none';
    s.classList.toggle('on', i < idx);
    s.classList.toggle('now', i === idx);
  });
}
function showCaptions(on) {
  $('#captions')?.classList.toggle('show', on);
  document.body.classList.toggle('captions-on', on);
}

/* ---------- playback ---------- */
let token = 0;
let fallbackSim = null;

function begin(who, id, label) {
  voiceState.speaking = true; voiceState.who = who; voiceState.id = id;
  document.body.classList.add('is-speaking', `speaking-${who}`);
  const s = $('#presenterStatus'); if (s && who === 'presenter') s.textContent = label || 'speaking';
  showCaptions(true);
  emit({ type: 'start', who, id });
}
function end(who) {
  voiceState.speaking = false; voiceState.open = 0;
  document.body.classList.remove('is-speaking', 'speaking-presenter', 'speaking-bot');
  const s = $('#presenterStatus'); if (s) s.textContent = 'tap to talk';
  emit({ type: 'end', who });
  setTimeout(() => { if (!voiceState.speaking) showCaptions(false); }, 1400);
}

/** Speak a line. { id, text (fallback TTS), src (source text, to detect stale clips), who, label } -> Promise<boolean> */
export async function say({ id, text, src, who = 'presenter', label } = {}) {
  stop(true);
  const my = ++token;
  if (voiceState.muted) return false;
  // 1) real video of Ravichandra speaking this line
  if (who === 'presenter' && id && await hasClip(id)) {
    if (my !== token) return false;
    const spoken = (text || '').split(/\s+/).filter(Boolean);
    const total = spoken.reduce((n, w) => n + w.length + 1, 0) || 1;
    let acc = 0;
    words = spoken.map((w) => { const s0 = acc / total; acc += w.length + 1; return [s0, acc / total, w]; });
    setCaption(words, text || '');
    lastIdx = -1;
    begin(who, id, label);
    const ok = await playClip(id, { onTime: (t, d) => { videoT = t / d; updateCaption(videoT); } });
    videoT = -1;
    if (my === token) end(who);
    return ok && my === token;
  }
  const m = id ? await meta(id) : null;
  if (my !== token) return false;
  // Ravichandra only ever speaks in his approved cloned voice: never a stand-in TTS voice
  if (who === 'presenter' && (!m || m.engine !== 'clone')) return false;
  if (m && (!src || m.src === src)) { // src mismatch = clip is stale -> TTS
    setCaption(m.words || [], m.text);
    audio.src = `assets/voice/${id}.mp3`;
    audio.currentTime = 0;
    begin(who, id, label);
    try { if (ctx?.state === 'suspended') await ctx.resume(); await audio.play(); }
    catch (e) { console.warn('play blocked', e); end(who); return false; }
    const ok = await new Promise((res) => {
      const done = (v) => { audio.onended = audio.onpause = audio.onerror = null; res(v); };
      audio.onended = () => done(true);
      audio.onerror = () => done(false);
      audio.onpause = () => { if (!audio.ended) done(false); };
    });
    if (my === token) end(who);
    return ok && my === token;
  }
  if (!text || who === 'presenter') return false;
  return ttsFallback(text, who, label, my);
}

/** Speak several clips back-to-back */
export async function sayAll(items) {
  for (const it of items) { const ok = await say(it); if (!ok) return false; }
  return true;
}

export function stop(silent) {
  token++;
  stopClip();
  if (!audio.paused) audio.pause();
  try { speechSynthesis.cancel(); } catch {}
  clearInterval(fallbackSim);
  if (voiceState.speaking && !silent) end(voiceState.who);
  voiceState.speaking = false;
}

export function setMuted(m) { voiceState.muted = m; if (m) stop(); emit({ type: 'mute', muted: m }); }

/* ---------- browser TTS fallback ---------- */
let ttsVoice = null;
function pickTTS() {
  const vs = speechSynthesis.getVoices();
  const pref = [/Prabhat.*Natural/i, /Neerja.*Natural/i, /en-IN/i, /Ravi/i, /Natural/i, /Google UK English Male/i];
  for (const re of pref) { ttsVoice = vs.find((v) => re.test(v.name) || re.test(v.lang)); if (ttsVoice) break; }
}
if ('speechSynthesis' in window) { pickTTS(); speechSynthesis.onvoiceschanged = pickTTS; }

function ttsFallback(text, who, label, my) {
  return new Promise((resolve) => {
    if (!('speechSynthesis' in window)) { resolve(false); return; }
    const u = new SpeechSynthesisUtterance(text.replace(/[\u{1F300}-\u{1FAFF}☀-➿]/gu, ''));
    if (ttsVoice) { u.voice = ttsVoice; u.lang = ttsVoice.lang; }
    u.rate = 1;
    setCaption([], text);
    const t0 = performance.now();
    u.onstart = () => {
      begin(who, null, label);
      fallbackSim = setInterval(() => {
        const t = (performance.now() - t0) / 1000;
        voiceState.open = 0.25 + Math.abs(Math.sin(t * 11)) * 0.5 * Math.abs(Math.sin(t * 3.3));
      }, 40);
    };
    const fin = (ok) => { clearInterval(fallbackSim); if (my === token) end(who); resolve(ok && my === token); };
    u.onend = () => fin(true); u.onerror = () => fin(false);
    speechSynthesis.speak(u);
  });
}

/* ---------- per-frame: lip-sync from waveform + captions ---------- */
function frame() {
  requestAnimationFrame(frame);
  if (!voiceState.speaking || audio.paused) return;
  const t = audio.currentTime;
  updateCaption(t);
  let level = 0;
  if (analyser) {
    analyser.getFloatTimeDomainData(buf);
    let sum = 0;
    for (let i = 0; i < buf.length; i++) sum += buf[i] * buf[i];
    level = Math.sqrt(sum / buf.length);
  }
  // word gating: close the mouth between words
  let inWord = !words.length;
  for (let i = 0; i < words.length; i++) if (t >= words[i][0] - 0.03 && t <= words[i][1] + 0.02) { inWord = true; break; }
  const o = Math.min(1, Math.max(0, (level - 0.015) * 7.5));
  voiceState.open = (analyser ? o : 0.3 + Math.abs(Math.sin(t * 12)) * 0.4) * (inWord ? 1 : 0.15);
}
requestAnimationFrame(frame);
